# Generated by Django 3.1.3 on 2020-11-27 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='socialinfo',
            new_name='student_data',
        ),
    ]
