# Generated by Django 3.1.3 on 2020-11-27 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20201127_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_data',
            name='department_id',
            field=models.IntegerField(default=0),
        ),
    ]
