# Generated by Django 3.2 on 2021-04-13 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_userinfo_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='img',
        ),
    ]
