# Generated by Django 3.1 on 2020-08-23 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0002_auto_20200823_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_form',
            name='name',
            field=models.CharField(default='faiz', max_length=50),
        ),
    ]
