# Generated by Django 3.1 on 2020-08-24 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0003_auto_20200823_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_form',
            name='gmail',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='contact_form',
            name='message',
            field=models.CharField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='contact_form',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
