# Generated by Django 3.1 on 2020-08-23 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_form',
            name='gmail',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='contact_form',
            name='message',
            field=models.CharField(default='', max_length=1500),
        ),
        migrations.AlterField(
            model_name='contact_form',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
