# Generated by Django 3.1 on 2020-12-03 10:00

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='event_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=100)),
                ('uni_name', models.CharField(default='', max_length=500)),
                ('img', models.ImageField(upload_to='images/')),
                ('title', models.CharField(default='', max_length=500)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('date_start', models.CharField(default='', max_length=50)),
                ('date_end', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
