# Generated by Django 3.1 on 2020-12-03 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_info',
            name='date_end',
            field=models.CharField(default='2011-09-19 02:40 PM', max_length=100),
        ),
        migrations.AlterField(
            model_name='event_info',
            name='date_start',
            field=models.CharField(default='2011-08-19 02:40 PM', max_length=50),
        ),
        migrations.AlterField(
            model_name='event_info',
            name='uni_name',
            field=models.CharField(default='u', max_length=500),
        ),
        migrations.AlterField(
            model_name='event_info',
            name='username',
            field=models.CharField(default='u', max_length=100),
        ),
    ]
