# Generated by Django 3.1 on 2020-12-04 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_event_info_uni_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_info',
            name='department_name',
            field=models.CharField(default='u', max_length=200),
        ),
    ]
