# Generated by Django 3.1.3 on 2020-11-27 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='socialinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=150)),
                ('student_id', models.CharField(max_length=150)),
                ('uni_name', models.CharField(max_length=150)),
                ('department_name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='userinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=150)),
                ('img', models.ImageField(upload_to='uploads/% Y/% m/% d/')),
                ('fullname', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=1000)),
                ('mobile_num', models.CharField(max_length=1000)),
                ('work', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
