# Generated by Django 3.1.3 on 2020-11-27 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_student_data_department_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_data',
            name='department_id',
            field=models.CharField(max_length=150),
        ),
    ]
