# Generated by Django 3.1.3 on 2020-11-28 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20201127_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_data',
            name='department_id',
            field=models.IntegerField(default=0),
        ),
    ]
