# Generated by Django 3.1.3 on 2020-11-21 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='num',
        ),
        migrations.AddField(
            model_name='category',
            name='uni_category',
            field=models.CharField(choices=[('pu', 'pulic'), ('pr', 'private'), ('me', 'medical'), ('en', 'Engineer')], default='', max_length=2),
        ),
    ]
