# Generated by Django 3.1.3 on 2020-11-22 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20201121_0726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='university_category',
        ),
    ]
