# Generated by Django 3.1.3 on 2020-11-23 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_remove_category_university_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='uni_category',
            new_name='university_category',
        ),
    ]
