# Generated by Django 3.1 on 2020-12-03 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20201203_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event_info',
            name='uni_name',
        ),
        migrations.AddField(
            model_name='event_info',
            name='department_id',
            field=models.IntegerField(default=0),
        ),
    ]
