# Generated by Django 3.1 on 2020-08-24 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='university',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='uploads/% Y/% m/% d/')),
                ('university_name', models.CharField(max_length=150)),
                ('university_description', models.CharField(max_length=1000)),
                ('details', models.URLField(max_length=128)),
                ('catagory', models.CharField(choices=[('F', 'Foreign'), ('B', 'Bangladesh')], max_length=1)),
            ],
        ),
    ]
