# Generated by Django 3.1.3 on 2020-11-26 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sub_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_name', models.CharField(default='', max_length=300, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='uni_cat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uni_category', models.CharField(choices=[('ag', 'Agricultural'), ('en', 'Engineer'), ('pu', 'public'), ('pr', 'private'), ('me', 'medical'), ('st', 'Science and Technology universities'), ('su', 'Specialised universities')], default='', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='unilist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_name', models.CharField(default='', max_length=300, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='university_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_logo', models.ImageField(upload_to='images/')),
                ('established_year', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=5000)),
                ('application_link', models.CharField(max_length=500)),
                ('total_department', models.IntegerField(default=0)),
                ('total_teacher', models.IntegerField(default=0)),
                ('total_student', models.IntegerField(default=0)),
                ('uni_category', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='university.uni_cat')),
                ('uni_name', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='university.unilist')),
            ],
        ),
        migrations.CreateModel(
            name='department_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_logo', models.ImageField(upload_to='images/')),
                ('established_year', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=5000)),
                ('total_achievment', models.IntegerField(default=0)),
                ('total_teacher', models.IntegerField(default=0)),
                ('total_student', models.IntegerField(default=0)),
                ('department_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.sub_list')),
                ('university_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.unilist')),
            ],
        ),
    ]
