# Generated by Django 3.1 on 2020-08-24 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='country',
            field=models.CharField(choices=[('F', 'Foreign'), ('B', 'Bangladesh')], default='', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='university',
            name='catagory',
            field=models.CharField(choices=[('Pu', 'Public'), ('Pr', 'Private'), ('En', 'Engineering'), ('Me', 'Medical')], max_length=3),
        ),
    ]
