# Generated by Django 3.1.3 on 2020-11-26 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_unilist_uni_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unilist',
            name='uni_category',
        ),
    ]
