# Generated by Django 3.1.3 on 2020-11-26 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0003_remove_unilist_uni_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='unilist',
            new_name='university_name',
        ),
        migrations.RenameField(
            model_name='department_list',
            old_name='university_name',
            new_name='uni_name',
        ),
    ]
