# Generated by Django 3.1.3 on 2020-11-26 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0005_auto_20201126_1033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department_list',
            name='department_logo',
        ),
    ]
