# Generated by Django 3.1.3 on 2020-11-28 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0006_remove_department_list_department_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='achievment_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=250)),
                ('department_id', models.IntegerField(default=0)),
                ('img', models.ImageField(upload_to='images/')),
                ('title', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=5000)),
            ],
        ),
    ]
