# Generated by Django 3.1.3 on 2020-11-28 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0008_auto_20201128_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievment_list',
            name='username',
            field=models.CharField(default='', max_length=150),
        ),
    ]
