# Generated by Django 3.1.3 on 2020-11-29 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0010_auto_20201129_0655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uni_cat',
            name='image',
        ),
        migrations.AlterField(
            model_name='uni_cat',
            name='uni_category',
            field=models.CharField(choices=[('ag', 'Agricultural'), ('en', 'Engineer'), ('pu', 'public'), ('pr', 'private'), ('me', 'medical'), ('st', 'Science and Technology universities'), ('su', 'Specialised universities')], default='', max_length=2),
        ),
    ]
