# Generated by Django 3.1.3 on 2020-11-29 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0011_auto_20201129_0708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university_list',
            name='application_link',
            field=models.URLField(default=''),
        ),
    ]
