# Generated by Django 3.1.3 on 2020-12-01 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0013_auto_20201130_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievment_list',
            name='department_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='achievment_list',
            name='username',
            field=models.CharField(default='username', max_length=150),
        ),
    ]
