# Generated by Django 3.1 on 2020-12-03 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0014_auto_20201201_0748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department_list',
            name='total_achievment',
        ),
    ]
